//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FileTest.rc
//
#define IDI_FILE_TEST                   101
#define IDD_PAGE00_TRANSACTION          102
#define IDD_PAGE01_CREATE               103
#define IDD_PAGE02_NTCREATE             104
#define IDD_PAGE03_READWRITE            105
#define IDD_PAGE04_MAPPING              106
#define IDD_PAGE05_FILEOPS              107
#define IDD_PAGE06_NTFILEINFO           108
#define IDD_PAGE07_NTVOLINFO            109
#define IDD_PAGE08_EA                   110
#define IDD_PAGE09_SECURITY             111
#define IDD_PAGE10_LINKS                112
#define IDD_PAGE11_STREAMS              113
#define IDD_CREATE_DISPOSITION          115
#define IDD_DESIRED_ACCESS              116
#define IDD_SHARE_MODE                  117
#define IDD_FILE_ATTRIBUTES             118
#define IDD_FLAGS_DIALOG                119
#define IDD_TEST_DIALOG                 120
#define IDR_ACCELERATORS                121
#define IDR_ACE_MENU                    123
#define IDD_EA_EDITOR                   124
#define IDI_ICON_ERROR                  125
#define IDI_ICON_WARNING                126
#define IDI_ICON_INFORMATION            127
#define IDD_EAS_EDITOR                  128
#define IDR_FILL_DATA_MENU              129
#define IDD_VALUES_DIALOG_OLD           130
#define IDD_PRIVILEGES                  131
#define IDD_FILE_TEST                   132
#define IDD_OBJECT_ID_MORE              133
#define IDD_DATA_EDITOR                 137
#define IDD_HELP_ABOUT                  138
#define IDR_QUICK_ACCESS_SELECTION      139
#define IDD_CREATEFILE_FLAGS            139
#define IDD_FLAGS_AND_ATTRS             139
#define IDR_NTCREATEFILE_MENU           139
#define IDR_NTCREATE_MENU               139
#define IDI_ICON1                       140
#define IDI_ICON_WAIT                   140
#define IDD_COPY_FILE                   140
#define IDR_REQUEST_OPLOCK_MENU         141
#define IDD_FILE_ACTION                 141
#define IDD_FLAGS_DIALOG1               142
#define IDD_VALUES_DIALOG               142
#define IDI_RIGHT_ARROW                 143
#define IDD_HELP_ABOUT1                 143
#define IDD_OBJECT_GUID_HELP            143
#define IDR_ACL_TYPE_MENU               144
#define IDS_INTEGRITY_LEVEL             145
#define IDR_DELETE_DIRECTORY_MENU       145
#define IDC_FILE_ATTRIBUTE_READONLY     800
#define IDC_FILE_ATTRIBUTE_HIDDEN       801
#define IDC_FILE_ATTRIBUTE_SYSTEM       802
#define IDC_OLD_DOS_VOLID               803
#define IDC_FILE_ATTRIBUTE_DIRECTORY    804
#define IDC_FILE_ATTRIBUTE_ARCHIVE      805
#define IDC_FILE_ATTRIBUTE_DEVICE       806
#define IDC_FILE_ATTRIBUTE_NORMAL       807
#define IDC_FILE_ATTRIBUTE_TEMPORARY    808
#define IDC_FILE_ATTRIBUTE_SPARSE_FILE  809
#define IDC_FILE_ATTRIBUTE_REPARSE_POINT 810
#define IDC_FILE_ATTRIBUTE_COMPRESSED   811
#define IDC_FILE_ATTRIBUTE_OFFLINE      812
#define IDC_FILE_ATTRIBUTE_NOT_CONTENT_INDEXED 813
#define IDC_FILE_ATTRIBUTE_ENCRYPTED    814
#define IDC_FILE_ATTRIBUTE_INTEGRITY_STREAM 815
#define IDC_SECURITY_SQOS_PRESENT       816
#define IDC_SECURITY_EFFECTIVE_ONLY     817
#define IDC_SECURITY_CONTEXT_TRACKING   818
#define IDC_SECURITY_ANONYMOUS          819
#define IDC_SECURITY_IDENTIFICATION     820
#define IDC_SECURITY_IMPERSONATION      821
#define IDC_SECURITY_DELEGATION         822
#define IDC_FILE_FLAG_OPEN_REPARSE_POINT 823
#define IDC_FILE_FLAG_POSIX_SEMANTICS   824
#define IDC_FILE_FLAG_BACKUP_SEMANTICS  825
#define IDC_FILE_FLAG_DELETE_ON_CLOSE   826
#define IDC_FILE_FLAG_SEQUENTIAL_SCAN   827
#define IDC_FILE_FLAG_RANDOM_ACCESS     828
#define IDC_FILE_FLAG_NO_BUFFERING      829
#define IDC_FILE_FLAG_OVERLAPPED        830
#define IDC_FILE_FLAG_WRITE_THROUGH     831
#define IDC_DESIRED_ACCESS_BROWSE       1002
#define IDC_FILE_ATTRIBUTES_BROWSE      1003
#define IDC_SHARE_ACCESS_BROWSE         1004
#define IDC_CREATE_OPTIONS_BROWSE       1005
#define IDC_OBJ_ATTR_FLAGS_BROWSE       1006
#define IDC_ALLOCATION_TYPE_BROWSE      1006
#define IDC_EXTENDED_ATTRIBUTES_EDIT    1007
#define IDC_LAST_ERROR                  1008
#define IDC_VERSION                     1009
#define IDC_READ_FILE                   1032
#define IDC_QUERY_INFO                  1032
#define IDC_MOVE_UP                     1032
#define IDC_CREATE_TRANSACTION          1032
#define IDC_CREATE_MAPPING              1032
#define IDC_QUERY_SECURITY              1032
#define IDC_SELECT_ALL                  1032
#define IDC_DESIRED_ACCESS              1033
#define IDC_MOVE_DOWN                   1033
#define IDC_QUERY_DIR                   1033
#define IDC_UNMAP_VIEW_OF_FILE          1033
#define IDC_SET_SECURITY                1033
#define IDC_CLEAR_ALL                   1033
#define IDC_NTREAD_FILE                 1033
#define IDC_INSERT                      1034
#define IDC_COMMIT_TRANSACTION          1034
#define IDC_ACCESS_DATA_READ            1034
#define IDC_SET_BLANK                   1034
#define IDC_NTWRITE_FILE                1034
#define IDC_FILE_ATTRIBUTES             1035
#define IDC_EDIT                        1035
#define IDC_ROLLBACK_TRANSACTION        1035
#define IDC_ACCESS_DATA_WRITE           1035
#define IDC_LOCK_FILE                   1035
#define IDC_CREATE_DISPOSITION          1036
#define IDC_DELETE                      1036
#define IDC_CLOSE_MAPPING               1036
#define IDC_UNLOCK_FILE                 1036
#define IDC_RADIO1                      1037
#define IDC_MAP_VIEW_OF_FILE            1037
#define IDC_NTLOCK_FILE                 1037
#define IDC_RADIO2                      1038
#define IDC_NTUNLOCK_FILE               1038
#define IDC_RADIO3                      1039
#define IDC_RADIO4                      1040
#define IDC_CHECKBOX                    1042
#define IDC_PAGE_READONLY               1043
#define IDC_CHECKBOX2                   1043
#define IDC_PAGE_READWRITE              1044
#define IDC_CHECKBOX3                   1044
#define IDC_FILE_MAP_READ               1045
#define IDC_CHECKBOX4                   1045
#define IDC_FILE_MAP_WRITE              1046
#define IDC_CHECKBOX5                   1046
#define IDC_ALLOCATION_SIZE             1047
#define IDC_CHECKBOX6                   1047
#define IDC_ALLOCATION_SIZE_UPDOWN      1048
#define IDC_CHECKBOX7                   1048
#define IDC_CLOSE_HANDLE                1049
#define IDC_CHECKBOX8                   1049
#define IDC_DIRECTORY_NAME              1050
#define IDC_CHECKBOX9                   1050
#define IDC_FILE_NAME                   1051
#define IDC_CHECKBOX10                  1051
#define IDC_FILE_NAME_BROWSE            1052
#define IDC_CHECKBOX11                  1052
#define IDC_DIRECTORY_NAME_BROWSE       1053
#define IDC_CHECKBOX12                  1053
#define IDC_SHARE_ACCESS                1054
#define IDC_CHECKBOX13                  1054
#define IDC_CREATE_OPTIONS              1055
#define IDC_TEMPLATE_FILE               1055
#define IDC_CHECKBOX14                  1055
#define IDC_TEMPLATE_FILE_BROWSE        1056
#define IDC_RELATIVE_FILE_HELP          1056
#define IDC_CHECKBOX15                  1056
#define IDC_RESULT_STATUS               1057
#define IDC_CHECKBOX16                  1057
#define IDC_NTCREATE_RESULT             1058
#define IDC_CHECKBOX17                  1058
#define IDC_CHECKBOX18                  1059
#define IDC_OBJ_ATTR_FLAGS              1060
#define IDC_CHECKBOX19                  1060
#define IDC_EXTENDED_ATTRIBUTES         1061
#define IDC_CHECKBOX20                  1061
#define IDC_CHECKBOX21                  1062
#define IDC_INTLEVEL_UPDOWN             1063
#define IDC_CHECKBOX22                  1063
#define IDC_CHECKBOX23                  1064
#define IDC_CHECKBOX24                  1065
#define IDC_FILE_DATA                   1066
#define IDC_CHECKBOX25                  1066
#define IDC_CHECKBOX26                  1067
#define IDC_CHECKBOX27                  1068
#define IDC_CHECKBOX28                  1069
#define IDC_WRITE_FILE                  1071
#define IDC_BYTES_TRANSFERRED           1072
#define IDC_FILL_DATA_MENU              1073
#define IDC_FILE_NAME1                  1074
#define IDC_FILE_NAME2                  1075
#define IDC_FILE_NAME1_BROWSE           1076
#define IDC_FILE_NAME2_BROWSE           1077
#define IDC_COPY_FILE                   1078
#define IDC_INCREASE_FILEPOS            1080
#define IDC_MOVE_FILE                   1080
#define IDC_DELETE_FILE                 1082
#define IDC_FILE_ID_GET                 1083
#define IDC_FILE_ID                     1084
#define IDC_OBJECT_ID_GET               1085
#define IDC_OBJECT_ID_MORE              1085
#define IDC_FILE_ID_USE                 1086
#define IDC_OBJECT_ID                   1087
#define IDC_SET_END_OF_FILE             1088
#define IDC_OBJECT_ID_USE               1088
#define IDC_GET_FILE_ATTRIBUTES         1089
#define IDC_DEFAULT                     1089
#define IDC_DEFAULT_LENGTH              1089
#define IDC_DELETE_DIRECTORY_MENU       1090
#define IDC_NT_QUERY_ATTRIBUTES_FILE    1091
#define IDC_FILE_INFO_CLASS             1093
#define IDC_IOSTATUS_INFO               1096
#define IDC_FILE_INFO                   1097
#define IDC_QUERY_EA                    1098
#define IDC_SET_EA                      1099
#define IDC_EA_LIST                     1100
#define IDC_DATA_NAME                   1101
#define IDC_QUERY_STREAMS               1101
#define IDC_DATA_VALUE_TEXT             1102
#define IDC_EXPORT_STREAMS              1102
#define IDC_DATA_VALUE_BIN              1103
#define IDC_IMPORT_STREAMS              1103
#define IDC_FLUSH_FILE_BUFFERS          1104
#define IDC_INPUT_LENGTH                1105
#define IDC_SET_SPARSE                  1105
#define IDC_SET_INFO                    1106
#define IDC_REQUEST_OPLOCK_MENU         1106
#define IDC_INPUT_LENGTH_TITLE          1107
#define IDC_REQUEST_OPLOCK_1            1107
#define IDC_COMMENT                     1108
#define IDC_REQUEST_OPLOCK_2            1108
#define IDC_MAXIMUM_LENGTH              1109
#define IDC_REQUEST_BATCH_OPLOCK        1109
#define IDC_REQUEST_FILTER_OPLOCK       1110
#define IDC_SEARCH_MASK                 1110
#define IDC_CREATE_TRANSACTION_HINT     1111
#define IDC_REQUEST_OPLOCK_WIN7         1111
#define IDC_BREAK_ACKNOWLEDGE_1         1112
#define IDC_COMMIT_TRANSACTION_HINT     1113
#define IDC_BREAK_ACKNOWLEDGE_2         1113
#define IDC_ROLLBACK_TRANSACTION_HINT   1114
#define IDC_CLOSE_HANDLE_HINT           1115
#define IDC_TRANSACTED                  1117
#define IDC_FS_INFO_CLASS               1119
#define IDC_VOL_INFO_CLASS              1119
#define IDC_QUERY_VOL_INFO              1120
#define IDC_SET_VOL_INFO                1121
#define IDC_BREAKPOINT                  1122
#define IDC_VIRTUALIZATION              1124
#define IDC_SECURITY_NAME               1125
#define IDC_GROUP_INFORMATION           1125
#define IDC_TAKE_OWNERSHIP_NAME         1126
#define IDC_OWNER_INFORMATION           1126
#define IDC_BACKUP_NAME                 1127
#define IDC_LABEL_INFORMATION           1127
#define IDC_RESTORE_NAME                1128
#define IDC_DACL_INFORMATION            1128
#define IDC_SECURITY                    1129
#define IDC_CHANGE_NOTIFY_NAME          1129
#define IDC_VALUES                      1130
#define IDC_MANAGE_VOLUME_NAME          1130
#define IDC_PRIVILEGES                  1131
#define IDC_TCB_NAME                    1131
#define IDC_CREATE_FILE                 1132
#define IDC_SACL_INFORMATION            1133
#define IDC_INTLEVEL_VALUE              1134
#define IDC_INTLEVEL_FRAME              1135
#define IDC_INTLEVEL_TITLE              1136
#define IDC_INTLEVEL_EXPLAIN            1137
#define IDC_EXIT                        1138
#define IDC_INTLEVEL_EXPLAIN2           1138
#define IDC_TAB                         1139
#define IDC_MAIN_FRAME                  1140
#define IDC_RESULT_FRAME                1141
#define IDC_LAST_ERROR_TITLE            1142
#define IDC_HANDLE_TITLE                1143
#define IDC_HANDLE                      1144
#define IDC_RESULT_STATUS_TITLE         1145
#define IDC_NTCREATE_RESULT_TITLE       1146
#define IDC_BYTES_TRANSFERRED_TITLE     1147
#define IDC_NTCREATE_RESULT_TITLE2      1147
#define IDC_FILEMAP_FRAME               1150
#define IDC_FILEID_FRAME                1151
#define IDC_OTHERS_FRAME                1152
#define IDC_FILE_INFO_CLASS_TITLE       1153
#define IDC_VOL_INFO_CLASS_TITLE        1154
#define IDC_OPEN_OPS_FRAME              1154
#define IDC_OPLOCKS_FRAME               1154
#define IDC_IOSTATUS_INFO_TITLE         1155
#define IDC_EA_TITLE                    1158
#define IDC_GET_FILE_SIZE               1160
#define IDC_SET_FILE_POINTER            1161
#define IDC_MOVEFILE_OPTIONS            1161
#define IDC_MOVE_OPTIONS                1161
#define IDC_SYMLINK_CREATE              1161
#define IDC_CREATE_OR_GET               1161
#define IDC_FILETEST_WEB                1161
#define IDC_SYMLINK                     1162
#define IDC_GET_OBJECT_ID               1162
#define IDC_COPY_OPTIONS                1162
#define IDC_SYMLINK_TARGET              1163
#define IDC_SET_OBJECT_ID               1163
#define IDC_SYMLINK_QUERY               1164
#define IDC_SYMLINK_DELETE              1165
#define IDC_SYMLINK_FRAME               1166
#define IDC_HARDLINK_FRAME              1167
#define IDC_HARDLINK_LIST               1168
#define IDC_NEW_HARDLINK                1169
#define IDC_HARDLINK_CREATE             1170
#define IDC_HARDLINK_QUERY              1171
#define IDC_HARDLINK_DELETE             1172
#define IDC_REPARSE_FRAME               1173
#define IDC_REPARSE                     1174
#define IDC_BYTE_OFFSET                 1175
#define IDC_REPARSE_CREATE              1176
#define IDC_LENGTH                      1176
#define IDC_REPARSE_QUERY               1177
#define IDC_LENGTH_TITLE                1177
#define IDC_REPARSE_DELETE              1178
#define IDC_BYTE_OFFSET_SPIN            1178
#define IDC_LENGTH_SPIN                 1179
#define IDC_BYTE_OFFSET_TITLE           1180
#define IDC_INTLEVEL_TEXT               1182
#define IDC_MAKE_DIRECTORY              1183
#define IDC_STREAMS_TITLE               1184
#define IDC_STREAMS_LIST                1185
#define IDC_GROUPBOX                    1186
#define IDC_BASE_ADDRESS                1187
#define IDC_SECTION_SIZE                1188
#define IDC_SECTION_SIZE_UPDOWN         1189
#define IDC_PAGE_PROTECTION             1190
#define IDC_ALLOCATION_ATTRIBUTES       1191
#define IDC_NTCREATE_SECTION            1192
#define IDC_NTOPEN_SECTION              1193
#define IDC_NTCLOSE                     1194
#define IDC_FILE_HANDLE                 1195
#define IDC_SECTION_FRAME               1196
#define IDC_SECTION_VIEW_FRAME          1197
#define IDC_WIN32_PROTECTION            1198
#define IDC_BASE_ADDRESS_UPDOWN         1199
#define IDC_COMMIT_SIZE                 1200
#define IDC_COMMIT_SIZE_UPDOWN          1201
#define IDC_VIEW_SIZE                   1202
#define IDC_VIEW_SIZE_UPDOWN            1203
#define IDC_ALLOCATION_TYPE             1204
#define IDC_MAP_VIEW                    1205
#define IDC_UNMAP_VIEW                  1206
#define IDC_MEM_COPY_READ               1207
#define IDC_DATA_EDITOR                 1207
#define IDC_MEM_COPY_READ2              1208
#define IDC_MEM_COPY_WRITE              1208
#define IDC_ALLOCATION_ATTRIBUTES_BROWSE 1209
#define IDC_SECTION_NAME                1210
#define IDC_SECTION_OFFSET              1211
#define IDC_SECTION_OFFSET_UPDOWN       1212
#define IDC_ADJUST_LENGTH               1213
#define IDC_INFORMATION                 1215
#define IDC_QUERY_INFO_SYNC             1216
#define IDC_QUERY_INFO_ASYNC            1217
#define IDC_READ_SYNC                   1218
#define IDC_READ_ASYNC                  1219
#define IDC_RDWR_SYNC                   1220
#define IDC_COPY_PROGRESS               1220
#define IDC_RDWR_ASYNC                  1221
#define IDC_COPY_INFO                   1222
#define IDC_COPY_METHOD                 1223
#define IDC_SIMPLE_DELETE               1223
#define IDC_FORCED_DELETE               1224
#define IDC_REPARSE_DATA                1226
#define IDC_CHILD_MUSTER                1227
#define IDC_BUTTON2                     1229
#define IDC_SEARCH_MASK_TITLE           1229
#define IDS_FLUSH_FILE_BUFFERS_TIP      4000
#define IDS_SET_SPARSE_TIP              4001
#define IDS_OPLOCK_BROKE                4002
#define IDS_FILE_INFO_CLASS             4003
#define IDS_VOLUME_INFO_CLASS           4004
#define IDS_NOFILESELECTED              4010
#define IDS_INVALIDACCESS               4011
#define IDS_OPERATIONCOMPLETE           4012
#define IDS_OPERATIONFAILED             4013
#define IDS_SELECT_DIRECTORY            4014
#define IDS_SELECT_FILE                 4015
#define IDS_FILTER_ALL                  4016
#define IDS_INVHANDLE                   4017
#define IDS_CLOSEFILEFIRST              4018
#define IDS_NULL                        4019
#define IDS_FILE_ATTRIBUTES_TEXT        4020
#define IDS_NO_FILENAME1                4021
#define IDS_NO_FILENAME2                4022
#define IDS_FILE_ATTRIBUTES             4023
#define IDS_APP_TITLE                   4024
#define IDS_DESIRED_ACCESS              4025
#define IDS_SHARE_ACCESS                4026
#define IDS_CREATE_OPTIONS              4027
#define IDS_MOVEFILE_FLAGS              4028
#define IDS_DATA_TRUNCATED              4029
#define IDS_BAD_DATETIME_FORMAT         4030
#define IDS_E_CANT_USE_DIRECTORY        4031
#define IDS_E_INVALID_NT_FILE_NAME      4032
#define IDS_E_INVALID_FILE_ID           4033
#define IDS_BAD_TIME_FORMAT             4034
#define IDS_TIME_FORMAT_PREFIX          4034
#define IDS_EXIT                        4035
#define IDS_OBJECT_ATTRIBUTES_FLAGS     4036
#define IDS_EA_NAME                     4037
#define IDS_EA_VALUE                    4038
#define IDS_CONVERSION_ERROR            4039
#define IDS_NO_EA_NAME                  4040
#define IDS_CONVERSION_ERROR_MSG        4041
#define IDS_E_VALUE_HAS_BAD_FORMAT      4042
#define IDS_DATE_FORMAT_PREFIX          4043
#define IDS_TRANSACTION_INACTIVE        4044
#define IDS_TRANSACTION_ACTIVE          4045
#define IDS_TRANSACTION_NONE            4046
#define IDS_FILE_BASIC_INFORMATION      4047
#define IDS_STREAM_TYPE                 4048
#define IDS_APP_TITLE_VISTA1            4049
#define IDS_APP_TITLE_VISTA2            4050
#define IDS_EA_INFO                     4051
#define IDS_EDIT_EA_TITLE               4052
#define IDS_INSERT_EA_TITLE             4053
#define IDS_STREAM_NAME                 4054
#define IDS_ACE_FLAGS                   4055
#define IDS_ACE_MASK                    4056
#define IDS_ACE_TYPE                    4057
#define IDS_NOT_PRESENT                 4058
#define IDS_STREAM_DATA                 4059
#define IDS_FAILED_TO_SAVE_FILE         4060
#define IDS_FAILED_TO_OPEN_STREAM       4061
#define IDS_FAILED_TO_SET_ILEVEL        4062
#define IDS_MANDATORY_MASK              4063
#define IDS_E_OPEN_TOKEN                4064
#define IDS_EMPTY_STREAM                4065
#define IDS_ENTER_DIRECTORY_NAME        4066
#define IDS_RELATIVE_FILE               4067
#define IDS_RELATIVE_FILE1              4067
#define IDS_RELATIVE_FILE_HELP          4067
#define IDS_RELATIVE_FILE2              4068
#define IDS_CHOOSE_REPARSE_TAG          4068
#define IDS_RELATIVE_FILE3              4069
#define IDS_ACE_TYPE_NOT_SUPPORTED      4069
#define IDS_RELATIVE_FILE_TITLE         4070
#define IDS_DESIRED_ACCESS_RF           4071
#define IDS_OPEN_OPTIONS_RF             4072
#define IDS_SHARE_ACCESS_RF             4073
#define IDS_EA_SIZE                     4074
#define IDS_NT_QUERY_ATTRIBUTES_FILE_TIP 4075
#define IDS_GET_FILE_ATTRIBUTES_TIP     4076
#define IDS_ALLOCATION_ATTRIBUTES       4077
#define IDS_ALLOCATION_TYPE             4078
#define IDS_E_CONVERT_VALUE             4079
#define IDS_DATA_EXCEPTION              4080
#define IDS_E_CONVERT_TO_UINT32         4081
#define IDS_OPLOCK_FLAGS                4082
#define IDS_HELP_ABOUT                  4083
#define IDS_WANT_TRIM_DATA              4084
#define IDS_COPYFILE_FLAGS              4085
#define IDS_COPY_PROGRESS               4086
#define IDS_ADS_ACE_MASK                4086
#define IDS_COPY_CANCELLED              4087
#define IDS_CUSTOM_VALUE                4088
#define IDS_DATA_LENGTH                 4089
#define ID_EDIT_LABEL                   40001
#define ID_NEW_ACE_BEFORE               40008
#define ID_NEW_ACE_AFTER                40009
#define ID_MOVE_ACE_DOWN                40010
#define ID_MOVE_ACE_UP                  40011
#define ID_DELETE_ACE                   40012
#define IDC_NEW_ACE_BEFORE              40013
#define IDC_NEW_ACE_AFTER               40014
#define IDC_MOVE_ACE_UP                 40015
#define IDC_MOVE_ACE_DOWN               40016
#define IDC_DELETE_ACE                  40017
#define ID_DOUBLE_CLICK                 40018
#define ID_CONTEXT_MENU                 40020
#define IDC_FILL_DATA_ZEROS             40028
#define IDC_FILL_DATA_PATTERN           40029
#define IDC_FILL_DATA_RANDOM            40030
#define IDC_FILL_DATA_CUSTOM            40031
#define ID__1                           40039
#define ID__2                           40040
#define ID__3                           40041
#define ID__4                           40042
#define ID__7                           40043
#define IDC_DELETE_ON_CLOSE             40044
#define ID_Menu                         40052
#define ID__SETTONULLDACL               40053
#define IDC_SET_NULL_ACL                40054
#define ID__SETTOEMPTYACL               40055
#define ID__CANCEL                      40056
#define IDC_DO_NOTHING                  40057
#define IDC_SET_EMPTY_DACL              40058
#define IDC_SET_EMPTY_ACL               40059
#define IDC_DELETE_DIRECTORY_SINGLE     40060
#define IDC_DELETE_DIRECTORY_TREE       40061

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        146
#define _APS_NEXT_COMMAND_VALUE         40062
#define _APS_NEXT_CONTROL_VALUE         1230
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
